USE customer_shopping_behaviour;
SELECT * FROM beh LIMIT 40;

# 1. What is the total revenue generated by male vs. female customers ?

SELECT gender ,SUM(purchase_amount) AS Revenue FROM beh
GROUP BY gender
ORDER BY Revenue DESC;

# 2.Which customers used a discount but still spent more than the average purchase amt ?

SELECT customer_id, purchase_amount FROM beh
WHERE discount_applied = 'Yes'AND purchase_amount >= (SELECT AVG(purchase_amount) FROM beh);

# 3. Which are the top 5 products with the highest average review rating ?

SELECT item_purchased, avg(review_rating) AS AVG_REV_RAT FROM beh
group by item_purchased
ORDER BY AVG_REV_RAT DESC
LIMIT 5;

# 4. Compare the average purchase amounts between standard and express shipping . 

SELECT ROUND(AVG(purchase_amount),2) AS AVG_pur_amt,shipping_type FROM beh
WHERE shipping_type in ('Standard','Express')
group by shipping_type;

# 5. Do subscribed customers spend more ? Compare average spend
# and total review between subscribers and non subscribers .

SELECT subscription_status,
COUNT(customer_id) AS total_customers ,
ROUND(AVG(purchase_amount),2) AS AVG_Spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM beh
GROUP BY subscription_status
ORDER BY total_revenue,AVG_Spend DESC;

# 6. Which 5 products have the highest percentage of purchases with discounts applied ? 

SELECT item_purchased,
ROUND(SUM(CASE WHEN  discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*)* 100,2) AS discount_rate
FROM beh
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
